document.write('<ul>');
document.write('<li id="b_top"><a href="/index.html"></a></li>');
document.write('<li id="b_equ"><a href="/equipment/index.html"></a></li>');
document.write('<li id="b_nagoya"><a href="/equipment/nagoya/index.html"></a></li>');
document.write('<li id="b_aod"><a href="/equipment/nagoya/nag_equip.html#1"></a></li>');
document.write('<li id="b_cent"><a href="/equipment/nagoya/nag_equip.html#1"></a></li>');
document.write('<li id="b_machine"><a href="/equipment/nagoya/nag_equip.html#2"></a></li>');
//document.write('<li id="b_ppw"><a href="/equipment/nagoya/nag_equip.html#2"></a></li>');
document.write('<li id="b_radio"><a href="/equipment/nagoya/nag_equip.html#3"></a></li>');
document.write('<li id="b_three"><a href="/equipment/nagoya/nag_equip.html#3"></a></li>');
document.write('<li id="b_nakatsu"><a href="/equipment/nakatsu/index.html"></a></li>');
document.write('<li id="b_cad"><a href="/equipment/nakatsu/nak_equip.html#1"></a></li>');
document.write('<li id="b_manufactur"><a href="/equipment/nakatsu/nak_equip.html#1"></a></li>');
document.write('<li id="b_injection"><a href="/equipment/nakatsu/nak_equip.html#2"></a></li>');
document.write('<li id="b_molding"><a href="/equipment/nakatsu/nak_equip.html#2"></a></li>');
document.write('<li id="b_casting_c"><a href="/equipment/nakatsu/nak_equip.html#3"></a></li>');
document.write('<li id="b_casting_l"><a href="/equipment/nakatsu/nak_equip.html#3"></a></li>');
document.write('<li id="b_dlcc"><a href="/equipment/nakatsu/nak_equip.html#4"></a></li>');
document.write('<ul>');
